### ISSUE TITLE
citygml-tools create WaterClosureSurfaces out of nowhere

### ISSUE THREAD

**Issue by MughtyWinky** [citygml4j/citygml-tools#54]
While converting a CityGML document, which only includes buildings, citygml-tools creates WaterClosureSurfaces onto WallSurfaces.

The following picture shows the original and converted data. 

![image](https://github.com/citygml4j/citygml-tools/assets/26003212/5fd0912a-f3a8-4516-8fe5-09c4cba54991)

[Link to Dataset](https://gds.hessen.de/downloadcenter/20240702/3D-Daten/3D-Geb%C3%A4udemodelle/3D-Geb%C3%A4udemodelle%20LoD2/Kreisfreie-Stadt-Frankfurt/Kreisfreie-Stadt-Frankfurt%20-%20LoD2.zip), tested on LoD2_Bergen-Enkheim.gml

**Comment by clausnagel** [comment]
Thanks for reporting. I fixed the bug with https://github.com/citygml4j/citygml4j/commit/1be3d9a156cd6022dcdf9d74d7c9894617355c4a.

Until a bugfix release is available, you can either build `citygml-tools` from source [following this guide](https://github.com/citygml4j/citygml-tools?tab=readme-ov-file#building) or use the `edge` Docker image from [here](https://hub.docker.com/r/citygml4j/citygml-tools).

**Comment by MughtyWinky** [comment]
Thanks for the quick response. Build it by myself using

```shell
git clone https://github.com/citygml4j/citygml-tools.git
cd citygml-tools
gradlew installDist
cd build
cd install
cd citygml-tools
copy c:\temp\LoD2_Bergen-Enkheim.gml .\
.\citygml-tools.bat to-cityjson LoD2_Bergen-Enkheim.gml
``` 

but the WaterClosureSurfaces are still present.

**Comment by clausnagel** [comment]
Sorry, my bad. One other commit was missing. Please `git pull` your local copy and rebuild.

**Comment by MughtyWinky** [comment]
Works fine now. Many thanks!
